### ISSUE TITLE
Process Overview Diagram

### ISSUE THREAD

**Issue by JeffreyDChau** [JeffreyDChau/ChessTablebase#1]
As a stakeholder, I want to understand the process of how each component of the application communicates with each other

- [x] Diagram in comments of issue

**Comment by jonathonkindle** [comment]
new diagram below

**Comment by jonathonkindle** [comment]
new diagram below

**Comment by jonathonkindle** [comment]
![Image](https://user-images.githubusercontent.com/46705433/216502166-d14d71cb-ba2c-4174-bc07-bb4c16959e19.png)
