### ISSUE TITLE
W6 Write functions to manage pieces on the board

### ISSUE THREAD

**Issue by MonaAtabanii** [JeffreyDChau/ChessTablebase#24]
As a user, I want to be able to move/delete and add pieces to the board.

**Comment by JeffreyDChau** [comment]
Due to a power outage, this message is from Mona: Added function to move pieces on the board.
![Image](https://user-images.githubusercontent.com/9541232/217993002-4a0f1b5f-5210-47cc-acdb-155c99614746.jpg)
Plan to add a trash feature for moving pieces outside the board.
