### ISSUE TITLE
Development Overview Diagram

### ISSUE THREAD

**Issue by JeffreyDChau** [JeffreyDChau/ChessTablebase#4]
As a stakeholder, I want to be able to understand what components are implemented application.

- [x] Diagram in comments of the issue

**Comment by ogarmela** [comment]
![Image](https://user-images.githubusercontent.com/52357639/214484185-fdb63371-7aca-4f25-8a3b-22cccc8f024a.png)

**Comment by ogarmela** [comment]
review
