### ISSUE TITLE
Scenerio Overview Diagram

### ISSUE THREAD

**Issue by JeffreyDChau** [JeffreyDChau/ChessTablebase#5]
As a stakeholder, I want to understand the sequences of interactions between each process of the application

- [x] Diagram in comments of issue

**Comment by MonaAtabanii** [comment]
1st version of the diagram, need to update the scenario concept




![Image](https://user-images.githubusercontent.com/42449312/214986891-1214403f-b906-4414-a29c-a504f15b9a4f.png)

**Comment by MonaAtabanii** [comment]
Edited and updated diagram 


![Image](https://user-images.githubusercontent.com/42449312/216464812-71a1b751-1ad0-4538-a1b3-d3ff83a5c700.jpeg)

**Comment by MonaAtabanii** [comment]
V3


![Image](https://user-images.githubusercontent.com/42449312/216491727-f9806f36-7a35-48a4-999f-cc1236a5c7c6.png)
